"use strict";

module.exports = {
  API_URI: require("./API_URI"),
  API_PORT: require("./API_PORT"),

  AUTH_URI: require("./AUTH_URI"),

  ...require("./WEBSITE_DOMAIN"),

  STORAGE_URI: require("./STORAGE_URI"),

  MONGODB_URI: require("./MONGODB_URI"),

  NODE_ENV: require("./NODE_ENV"),
  RELEASE_ENV: require("./RELEASE_ENV"),

  REDIS_URI: require("./REDIS_URI"),

  SENTRY_DSN: require("./SENTRY_DSN"),

  VONAGE_API_KEY: require("./VONAGE_API_KEY"),
  VONAGE_API_SECRET: require("./VONAGE_API_SECRET"),
  VONAGE_APPLICATION_ID: require("./VONAGE_APPLICATION_ID"),

  ...require("./MAILGUN"),
  MAILGUN_PRIVATE_API_KEY: require("./MAILGUN_PRIVATE_API_KEY"),
  MAILGUN_PUBLIC_VALIDATION_KEY: require("./MAILGUN_PUBLIC_VALIDATION_KEY"),
  MAILGUN_WEBHOOK_SIGNING_KEY: require("./MAILGUN_WEBHOOK_SIGNING_KEY"),

  ADMIN_CLIENT_ID: require("./ADMIN_CLIENT_ID"),
  ADMIN_CLIENT_SECRET: require("./ADMIN_CLIENT_SECRET"),
  ADMIN_CLIENT_REDIRECT_URI: require("./ADMIN_CLIENT_REDIRECT_URI"),

  WEBSITE_CLIENT_ID: require("./WEBSITE_CLIENT_ID"),
  WEBSITE_CLIENT_SECRET: require("./WEBSITE_CLIENT_SECRET"),
  WEBSITE_CLIENT_REDIRECT_URI: require("./WEBSITE_CLIENT_REDIRECT_URI"),
};
