name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    timeout-minutes: 10

    env:
      NODE_VERSION: 18.x

    steps:
      - uses: actions/checkout@v2

      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Compatible TypeScript Version
        run: npm i typescript@4.9.5 --save-dev

      - name: Install Packages
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build

      # - name: Test
      #   run: npm run test:ci

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     env_vars: NODE_VERSION
      #     fail_ci_if_error: true
