version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: btcex-web-app
    container_name: btcex-web-app
    restart: unless-stopped
    env_file: .env
    environment:
      - API_PORT=3000
    ports:
      - "80:3000"
    volumes:
      - .:/home/node
      - node-modules:/home/node/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node-modules:
