"use strict";

const dotenv = require("dotenv");

dotenv.config();

module.exports = {
  API_URI: require("./API_URI"),
  API_PORT: require("./API_PORT"),

  AUTH_URI: require("./AUTH_URI"),

  ...require("./WEBSITE_DOMAIN"),


  STORAGE_URI: require("./STORAGE_URI"),

  MONGODB_URI: require("./MONGODB_URI"),

  NODE_ENV: require("./NODE_ENV"),
  RELEASE_ENV: require("./RELEASE_ENV"),

  REDIS_URI: require("./REDIS_URI"),

  SENTRY_DSN: require("./SENTRY_DSN"),

  BITGO_ACCESS_TOKEN: require("./BITGO_ACCESS_TOKEN"),
  BITGO_API_URI: require("./BITGO_API_URI"),

  VAULTODY_API_KEY: require("./VAULTODY_API_KEY"),
  VAULTODY_API_SECRET: require("./VAULTODY_API_SECRET"),
  VAULTODY_API_PASSPHRASE: require("./VAULTODY_API_PASSPHRASE"),
  VAULTODY_API_URI: require("./VAULTODY_API_URI"),
  VAULTODY_CALLBACK_SECRET_KEY: require("./VAULTODY_CALLBACK_SECRET_KEY"),
  VAULTODY_WEBHOOK_URL: require("./VAULTODY_WEBHOOK_URL"),
  VAULTODY_GENERAL_VAULT_ID: require("./VAULTODY_GENERAL_VAULT_ID"),
  VAULTODY_AUTOMATION_VAULT_ID: require("./VAULTODY_AUTOMATION_VAULT_ID"),


  S3_ACCESS_KEY_ID: require("./S3_ACCESS_KEY_ID"),
  S3_BUCKET: require("./S3_BUCKET"),
  S3_ENDPOINT: require("./S3_ENDPOINT"),
  S3_REGION: require("./S3_REGION"),
  S3_SECRET_ACCESS_KEY: require("./S3_SECRET_ACCESS_KEY"),

  VONAGE_API_KEY: require("./VONAGE_API_KEY"),
  VONAGE_API_SECRET: require("./VONAGE_API_SECRET"),
  VONAGE_APPLICATION_ID: require("./VONAGE_APPLICATION_ID"),

  MAILGUN_SENDING_DOMAIN: require("./MAILGUN_SENDING_DOMAIN"),
  ...require("./MAILGUN"),
  MAILGUN_PRIVATE_API_KEY: require("./MAILGUN_PRIVATE_API_KEY"),
  MAILGUN_PUBLIC_VALIDATION_KEY: require("./MAILGUN_PUBLIC_VALIDATION_KEY"),
  MAILGUN_WEBHOOK_SIGNING_KEY: require("./MAILGUN_WEBHOOK_SIGNING_KEY"),


  WEBSITE_CLIENT_ID: require("./WEBSITE_CLIENT_ID"),
  WEBSITE_CLIENT_SECRET: require("./WEBSITE_CLIENT_SECRET"),
  WEBSITE_CLIENT_REDIRECT_URI: require("./WEBSITE_CLIENT_REDIRECT_URI"),
  WEBSITE_CLIENT_URI: require('./WEBSITE_CLIENT_URI'),

  ADMIN_CLIENT_ID: require("./ADMIN_CLIENT_ID"),
  ADMIN_CLIENT_SECRET: require("./ADMIN_CLIENT_SECRET"),
  ADMIN_CLIENT_REDIRECT_URI: require("./ADMIN_CLIENT_REDIRECT_URI"),
  WEB_SOCKET_SERVER_PORT: require("./WEB_SOCKET_SERVER_PORT"),

  SCRYPT_API_KEY: require("./SCRYPT_API_KEY"),
  SCRYPT_API_SECRET: require("./SCRYPT_API_SECRET"),
  SCRYPT_WS_URI: require("./SCRYPT_WS_URI"),
  SCRYPT_HTTPS_URI: require("./SCRYPT_HTTPS_URI"),

  BITSTAMP_HTTP_API_URL: require('./BITSTAMP_HTTP_API_URL'),
  BITSTAMP_API_KEY: require('./BITSTAMP_API_KEY'),
  BITSTAMP_API_SECRET: require('./BITSTAMP_API_SECRET'),

  KRAKEN_HTTP_API_URL: require('./KRAKEN_HTTP_API_URL'),
  KRAKEN_API_KEY: require('./KRAKEN_API_KEY'),
  KRAKEN_PRIVATE_KEY: require('./KRAKEN_PRIVATE_KEY'),

  COIN_CONVERT_HTTP_API_URL: require('./COIN_CONVERT_HTTP_API_URL'),

  TWILIO_ACCOUNT_SID: require('./TWILIO_ACCOUNT_SID'),
  TWILIO_AUTH_TOKEN: require('./TWILIO_AUTH_TOKEN'),
  TWILIO_PHONE: require('./TWILIO_PHONE'),

  HCAPTCHA_SECRET_KEY: require('./HCAPTCHA_SECRET_KEY'),
  HCAPTCHA_SITE_VERIFY_URL : require('./HCAPTCHA_SITE_VERIFY_URL'),
};
