"use strict";

const KYC_IDENTIFICATION_TYPE = {
  PASSPORT: "PASSPORT",
  IDENTITY_CARD: "IDENTITY_CARD",
  DRIVING_LICENSE: "DRIVING_LICENSE",
};
const WAITING_LIST_IDENTIFICATION_TYPE ={
  PASSPORT: "PASSPORT",
  IDENTITY_CARD: "IDENTITY_CARD",
  DRIVING_LICENSE: "DRIVING_LICENSE",
  '': ''
}


const KYC_STATUS = {
  PENDING: "PENDING",
  VERIFIED: "VERIFIED",
  CANCELED: "CANCELED",
  FAILED: "FAILED",
  EXPIRED: "EXPIRED",
  UNVERIFIED : "UNVERIFIED"
};

const WAITING_LIST_STATUS ={
  PENDING: "PENDING",
  VERIFIED: "VERIFIED",
  CANCELED: "CANCELED",
  FAILED: "FAILED",
  EXPIRED: "EXPIRED",
  UNVERIFIED : "UNVERIFIED"
}

module.exports = {
  KYC_STATUS,
  KYC_IDENTIFICATION_TYPE,
  WAITING_LIST_STATUS,
  WAITING_LIST_IDENTIFICATION_TYPE
};