"use strict";

const TOKEN_KIND = {
  ACCESS_TOKEN: "ACCESS_TOKEN",
  AUTHORIZATION_CODE: "AUTHORIZATION_CODE",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  CLIENT_CREDENTIALS: "CLIENT_CREDENTIALS",
  INITIAL_ACCESS_TOKEN: "INITIAL_ACCESS_TOKEN",
  REGISTRATION_ACCESS_TOKEN: "REGISTRATION_ACCESS_TOKEN",
  DEVICE_CODE: "DEVICE_CODE",
};

const TOKEN_GTY = {
  IMPLICIT: "IMPLICIT",
  AUTHORIZATION_CODE: "AUTHORIZATION_CODE",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  DEVICE_CODE: "DEVICE_CODE",
};

module.exports = {
  TOKEN_KIND,
  TOKEN_GTY,
};
