"use strict";

const TRANSACTION_KIND = {
  DEPOSIT: "DEPOSIT",
  TRANSFER: "TRANSFER",
  WITHDRAW: "WITHDRAW",
  MANUAL_DEPOSIT: "MANUAL_DEPOSIT",
  MANUAL_WITHDRAW: "MANUAL_WITHDRAW",
};

const TRANSACTION_STATUS = {
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  EXPIRED: "EXPIRED",
  REJECTED: 'REJECTED'
};

const CRYPTO_TRANSACTION_STATUS = {
  AWAIT_APPROVAL: 'AWAIT_APPROVAL',
  BROADCASTED: 'BROADCASTED',
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REJECTED: 'REJECTED',
  MINED: 'MINED',
  CREATED: 'CREATED',
  PREPARED: 'PREPARED',
  SIGNED: 'SIGNED'
}


module.exports = {
  TRANSACTION_KIND,
  TRANSACTION_STATUS,
  CRYPTO_TRANSACTION_STATUS
};
