"use strict";

const CRYPTOAPIS_TRANSACTION_WALLET_FEE_PRIORITY = {
  STANDARD: "standard",
  SLOW: "slow",
  FAST: "fast",
};

const CRYPTO_TYPE ={
  COIN : "coin",
  TOKEN : "token",
}

const CRYPTO_TRANSACTION_REQUEST_STATUS ={
  APPROVED : "TRANSACTION_REQUEST_APPROVAL",
  REJECTED : "TRANSACTION_REQUEST_REJECTION",
  BROADCASTED: "TRANSACTION_REQUEST_BROADCASTED",
  MINED: "TRANSACTION_REQUEST_MINED",
  FAILED: "TRANSACTION_REQUEST_FAIL"
}

// List of Vaultody events
const VAULTODY_WEBHOOK_EVENTS = [
  'TRANSACTION_REQUEST',
  'TRANSACTION_APPROVED',
  'TRANSACTION_REJECTED',
  'INCOMING_CONFIRMED_COIN_TX',
  'INCOMING_CONFIRMED_TOKEN_TX',
  'INCOMING_CONFIRMED_INTERNAL_TX',
  'INCOMING_MINED_TX',
  'OUTGOING_FAILED',
  'OUTGOING_MINED',
  'TRANSACTION_BROADCASTED'
];

module.exports = {
  
  CRYPTO_TYPE,
  VAULTODY_WEBHOOK_EVENTS,
  CRYPTOAPIS_TRANSACTION_WALLET_FEE_PRIORITY,
  CRYPTO_TRANSACTION_REQUEST_STATUS
};
