# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    timeout-minutes: 10

    env:
      NODE_VERSION: 14.17.5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install packages
        run: npm i

      # - name: Lint
      #   run: npm run lint

      - name: Test
        run: npm run test:ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: NODE_VERSION
          fail_ci_if_error: true
