"use strict";

const { COLLECTION: NAME } = require("@src/constants");
const { connection: { db } } = require("mongoose");

// ------------------------- CONSTANTS --------------------------

const COUNTRIES = [
  {
    code: "AF",
    name: "Afghanistan",
    phone_code: "93",
    language: "fa-AF",
  },
  {
    code: "AX",
    name: "Aland Islands",
    phone_code: "+358-18",
    language: "sv-AX",
  },
  {
    code: "AL",
    name: "Albania",
    phone_code: "355",
    language: "sq",
  },
  {
    code: "DZ",
    name: "Algeria",
    phone_code: "213",
    language: "ar-DZ",
  },
  {
    code: "AS",
    name: "American Samoa",
    phone_code: "+1-684",
    language: "en-AS",
  },
  {
    code: "AD",
    name: "Andorra",
    phone_code: "376",
    language: "ca",
  },
  {
    code: "AO",
    name: "Angola",
    phone_code: "244",
    language: "pt-AO",
  },
  {
    code: "AI",
    name: "Anguilla",
    phone_code: "+1-264",
    language: "en-AI",
  },
  {
    code: "AG",
    name: "Antigua and Barbuda",
    phone_code: "+1-268",
    language: "en-AG",
  },
  {
    code: "AR",
    name: "Argentina",
    phone_code: "54",
    language: "es-AR",
  },
  {
    code: "AM",
    name: "Armenia",
    phone_code: "374",
    language: "hy",
  },
  {
    code: "AW",
    name: "Aruba",
    phone_code: "297",
    language: "nl-AW",
  },
  {
    code: "AU",
    name: "Australia",
    phone_code: "61",
    language: "en-AU",
  },
  {
    code: "AT",
    name: "Austria",
    phone_code: "43",
    language: "de-AT",
  },
  {
    code: "AZ",
    name: "Azerbaijan",
    phone_code: "994",
    language: "az",
  },
  {
    code: "BS",
    name: "Bahamas",
    phone_code: "+1-242",
    language: "en-BS",
  },
  {
    code: "BH",
    name: "Bahrain",
    phone_code: "973",
    language: "ar-BH",
  },
  {
    code: "BD",
    name: "Bangladesh",
    phone_code: "880",
    language: "bn-BD",
  },
  {
    code: "BB",
    name: "Barbados",
    phone_code: "+1-246",
    language: "en-BB",
  },
  {
    code: "BY",
    name: "Belarus",
    phone_code: "375",
    language: "be",
  },
  {
    code: "BE",
    name: "Belgium",
    phone_code: "32",
    language: "nl-BE",
  },
  {
    code: "BZ",
    name: "Belize",
    phone_code: "501",
    language: "en-BZ",
  },
  {
    code: "BJ",
    name: "Benin",
    phone_code: "229",
    language: "fr-BJ",
  },
  {
    code: "BM",
    name: "Bermuda",
    phone_code: "+1-441",
    language: "en-BM",
  },
  {
    code: "BT",
    name: "Bhutan",
    phone_code: "975",
    language: "dz",
  },
  {
    code: "BO",
    name: "Bolivia",
    phone_code: "591",
    language: "es-BO",
  },
  {
    code: "BQ",
    name: "Bonaire, Saint Eustatius and Saba ",
    phone_code: "599",
    language: "nl",
  },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    phone_code: "387",
    language: "bs",
  },
  {
    code: "BW",
    name: "Botswana",
    phone_code: "267",
    language: "en-BW",
  },
  {
    code: "BR",
    name: "Brazil",
    phone_code: "55",
    language: "pt-BR",
  },
  {
    code: "IO",
    name: "British Indian Ocean Territory",
    phone_code: "246",
    language: "en-IO",
  },
  {
    code: "VG",
    name: "British Virgin Islands",
    phone_code: "+1-284",
    language: "en-VG",
  },
  {
    code: "BN",
    name: "Brunei",
    phone_code: "673",
    language: "ms-BN",
  },
  {
    code: "BG",
    name: "Bulgaria",
    phone_code: "359",
    language: "bg",
  },
  {
    code: "BF",
    name: "Burkina Faso",
    phone_code: "226",
    language: "fr-BF",
  },
  {
    code: "BI",
    name: "Burundi",
    phone_code: "257",
    language: "fr-BI",
  },
  {
    code: "KH",
    name: "Cambodia",
    phone_code: "855",
    language: "km",
  },
  {
    code: "CM",
    name: "Cameroon",
    phone_code: "237",
    language: "en-CM",
  },
  {
    code: "CA",
    name: "Canada",
    phone_code: "1",
    language: "en-CA",
  },
  {
    code: "CV",
    name: "Cape Verde",
    phone_code: "238",
    language: "pt-CV",
  },
  {
    code: "KY",
    name: "Cayman Islands",
    phone_code: "+1-345",
    language: "en-KY",
  },
  {
    code: "CF",
    name: "Central African Republic",
    phone_code: "236",
    language: "fr-CF",
  },
  {
    code: "TD",
    name: "Chad",
    phone_code: "235",
    language: "fr-TD",
  },
  {
    code: "CL",
    name: "Chile",
    phone_code: "56",
    language: "es-CL",
  },
  {
    code: "CN",
    name: "China",
    phone_code: "86",
    language: "zh-CN",
  },
  {
    code: "CX",
    name: "Christmas Island",
    phone_code: "61",
    language: "en",
  },
  {
    code: "CC",
    name: "Cocos Islands",
    phone_code: "61",
    language: "ms-CC",
  },
  {
    code: "CO",
    name: "Colombia",
    phone_code: "57",
    language: "es-CO",
  },
  {
    code: "KM",
    name: "Comoros",
    phone_code: "269",
    language: "ar",
  },
  {
    code: "CK",
    name: "Cook Islands",
    phone_code: "682",
    language: "en-CK",
  },
  {
    code: "CR",
    name: "Costa Rica",
    phone_code: "506",
    language: "es-CR",
  },
  {
    code: "HR",
    name: "Croatia",
    phone_code: "385",
    language: "hr-HR",
  },
  {
    code: "CU",
    name: "Cuba",
    phone_code: "53",
    language: "es-CU",
  },
  {
    code: "CW",
    name: "Curacao",
    phone_code: "599",
    language: "nl",
  },
  {
    code: "CY",
    name: "Cyprus",
    phone_code: "357",
    language: "el-CY",
  },
  {
    code: "CZ",
    name: "Czech Republic",
    phone_code: "420",
    language: "cs",
  },
  {
    code: "CD",
    name: "Democratic Republic of the Congo",
    phone_code: "243",
    language: "fr-CD",
  },
  {
    code: "DK",
    name: "Denmark",
    phone_code: "45",
    language: "da-DK",
  },
  {
    code: "DJ",
    name: "Djibouti",
    phone_code: "253",
    language: "fr-DJ",
  },
  {
    code: "DM",
    name: "Dominica",
    phone_code: "+1-767",
    language: "en-DM",
  },
  {
    code: "DO",
    name: "Dominican Republic",
    phone_code: "+1-809 and 1-829",
    language: "es-DO",
  },
  {
    code: "TL",
    name: "East Timor",
    phone_code: "670",
    language: "tet",
  },
  {
    code: "EC",
    name: "Ecuador",
    phone_code: "593",
    language: "es-EC",
  },
  {
    code: "EG",
    name: "Egypt",
    phone_code: "20",
    language: "ar-EG",
  },
  {
    code: "SV",
    name: "El Salvador",
    phone_code: "503",
    language: "es-SV",
  },
  {
    code: "GQ",
    name: "Equatorial Guinea",
    phone_code: "240",
    language: "es-GQ",
  },
  {
    code: "ER",
    name: "Eritrea",
    phone_code: "291",
    language: "aa-ER",
  },
  {
    code: "EE",
    name: "Estonia",
    phone_code: "372",
    language: "et",
  },
  {
    code: "ET",
    name: "Ethiopia",
    phone_code: "251",
    language: "am",
  },
  {
    code: "FK",
    name: "Falkland Islands",
    phone_code: "500",
    language: "en-FK",
  },
  {
    code: "FO",
    name: "Faroe Islands",
    phone_code: "298",
    language: "fo",
  },
  {
    code: "FJ",
    name: "Fiji",
    phone_code: "679",
    language: "en-FJ",
  },
  {
    code: "FI",
    name: "Finland",
    phone_code: "358",
    language: "fi-FI",
  },
  {
    code: "FR",
    name: "France",
    phone_code: "33",
    language: "fr-FR",
  },
  {
    code: "GF",
    name: "French Guiana",
    phone_code: "594",
    language: "fr-GF",
  },
  {
    code: "PF",
    name: "French Polynesia",
    phone_code: "689",
    language: "fr-PF",
  },
  {
    code: "GA",
    name: "Gabon",
    phone_code: "241",
    language: "fr-GA",
  },
  {
    code: "GM",
    name: "Gambia",
    phone_code: "220",
    language: "en-GM",
  },
  {
    code: "GE",
    name: "Georgia",
    phone_code: "995",
    language: "ka",
  },
  {
    code: "DE",
    name: "Germany",
    phone_code: "49",
    language: "de",
  },
  {
    code: "GH",
    name: "Ghana",
    phone_code: "233",
    language: "en-GH",
  },
  {
    code: "GI",
    name: "Gibraltar",
    phone_code: "350",
    language: "en-GI",
  },
  {
    code: "GR",
    name: "Greece",
    phone_code: "30",
    language: "el-GR",
  },
  {
    code: "GL",
    name: "Greenland",
    phone_code: "299",
    language: "kl",
  },
  {
    code: "GD",
    name: "Grenada",
    phone_code: "+1-473",
    language: "en-GD",
  },
  {
    code: "GP",
    name: "Guadeloupe",
    phone_code: "590",
    language: "fr-GP",
  },
  {
    code: "GU",
    name: "Guam",
    phone_code: "+1-671",
    language: "en-GU",
  },
  {
    code: "GT",
    name: "Guatemala",
    phone_code: "502",
    language: "es-GT",
  },
  {
    code: "GG",
    name: "Guernsey",
    phone_code: "+44-1481",
    language: "en",
  },
  {
    code: "GW",
    name: "Guinea-Bissau",
    phone_code: "245",
    language: "pt-GW",
  },
  {
    code: "GN",
    name: "Guinea",
    phone_code: "224",
    language: "fr-GN",
  },
  {
    code: "GY",
    name: "Guyana",
    phone_code: "592",
    language: "en-GY",
  },
  {
    code: "HT",
    name: "Haiti",
    phone_code: "509",
    language: "ht",
  },
  {
    code: "HN",
    name: "Honduras",
    phone_code: "504",
    language: "es-HN",
  },
  {
    code: "HK",
    name: "Hong Kong",
    phone_code: "852",
    language: "zh-HK",
  },
  {
    code: "HU",
    name: "Hungary",
    phone_code: "36",
    language: "hu-HU",
  },
  {
    code: "IS",
    name: "Iceland",
    phone_code: "354",
    language: "is",
  },
  {
    code: "IN",
    name: "India",
    phone_code: "91",
    language: "en-IN",
  },
  {
    code: "ID",
    name: "Indonesia",
    phone_code: "62",
    language: "id",
  },
  {
    code: "IR",
    name: "Iran",
    phone_code: "98",
    language: "fa-IR",
  },
  {
    code: "IQ",
    name: "Iraq",
    phone_code: "964",
    language: "ar-IQ",
  },
  {
    code: "IE",
    name: "Ireland",
    phone_code: "353",
    language: "en-IE",
  },
  {
    code: "IM",
    name: "Isle of Man",
    phone_code: "+44-1624",
    language: "en",
  },
  {
    code: "IL",
    name: "Israel",
    phone_code: "972",
    language: "he",
  },
  {
    code: "IT",
    name: "Italy",
    phone_code: "39",
    language: "it-IT",
  },
  {
    code: "CI",
    name: "Ivory Coast",
    phone_code: "225",
    language: "fr-CI",
  },
  {
    code: "JM",
    name: "Jamaica",
    phone_code: "+1-876",
    language: "en-JM",
  },
  {
    code: "JP",
    name: "Japan",
    phone_code: "81",
    language: "ja",
  },
  {
    code: "JE",
    name: "Jersey",
    phone_code: "+44-1534",
    language: "en",
  },
  {
    code: "JO",
    name: "Jordan",
    phone_code: "962",
    language: "ar-JO",
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    phone_code: "7",
    language: "kk",
  },
  {
    code: "KE",
    name: "Kenya",
    phone_code: "254",
    language: "en-KE",
  },
  {
    code: "KI",
    name: "Kiribati",
    phone_code: "686",
    language: "en-KI",
  },
  {
    code: "XK",
    name: "Kosovo",
    phone_code: "383",
    language: "sq",
  },
  {
    code: "KW",
    name: "Kuwait",
    phone_code: "965",
    language: "ar-KW",
  },
  {
    code: "KG",
    name: "Kyrgyzstan",
    phone_code: "996",
    language: "ky",
  },
  {
    code: "LA",
    name: "Laos",
    phone_code: "856",
    language: "lo",
  },
  {
    code: "LV",
    name: "Latvia",
    phone_code: "371",
    language: "lv",
  },
  {
    code: "LB",
    name: "Lebanon",
    phone_code: "961",
    language: "ar-LB",
  },
  {
    code: "LS",
    name: "Lesotho",
    phone_code: "266",
    language: "en-LS",
  },
  {
    code: "LR",
    name: "Liberia",
    phone_code: "231",
    language: "en-LR",
  },
  {
    code: "LY",
    name: "Libya",
    phone_code: "218",
    language: "ar-LY",
  },
  {
    code: "LI",
    name: "Liechtenstein",
    phone_code: "423",
    language: "de-LI",
  },
  {
    code: "LT",
    name: "Lithuania",
    phone_code: "370",
    language: "lt",
  },
  {
    code: "LU",
    name: "Luxembourg",
    phone_code: "352",
    language: "lb",
  },
  {
    code: "MO",
    name: "Macao",
    phone_code: "853",
    language: "zh",
  },
  {
    code: "MK",
    name: "Macedonia",
    phone_code: "389",
    language: "mk",
  },
  {
    code: "MG",
    name: "Madagascar",
    phone_code: "261",
    language: "fr-MG",
  },
  {
    code: "MW",
    name: "Malawi",
    phone_code: "265",
    language: "ny",
  },
  {
    code: "MY",
    name: "Malaysia",
    phone_code: "60",
    language: "ms-MY",
  },
  {
    code: "MV",
    name: "Maldives",
    phone_code: "960",
    language: "dv",
  },
  {
    code: "ML",
    name: "Mali",
    phone_code: "223",
    language: "fr-ML",
  },
  {
    code: "MT",
    name: "Malta",
    phone_code: "356",
    language: "mt",
  },
  {
    code: "MH",
    name: "Marshall Islands",
    phone_code: "692",
    language: "mh",
  },
  {
    code: "MQ",
    name: "Martinique",
    phone_code: "596",
    language: "fr-MQ",
  },
  {
    code: "MR",
    name: "Mauritania",
    phone_code: "222",
    language: "ar-MR",
  },
  {
    code: "MU",
    name: "Mauritius",
    phone_code: "230",
    language: "en-MU",
  },
  {
    code: "YT",
    name: "Mayotte",
    phone_code: "262",
    language: "fr-YT",
  },
  {
    code: "MX",
    name: "Mexico",
    phone_code: "52",
    language: "es-MX",
  },
  {
    code: "FM",
    name: "Micronesia",
    phone_code: "691",
    language: "en-FM",
  },
  {
    code: "MD",
    name: "Moldova",
    phone_code: "373",
    language: "ro",
  },
  {
    code: "MC",
    name: "Monaco",
    phone_code: "377",
    language: "fr-MC",
  },
  {
    code: "MN",
    name: "Mongolia",
    phone_code: "976",
    language: "mn",
  },
  {
    code: "ME",
    name: "Montenegro",
    phone_code: "382",
    language: "sr",
  },
  {
    code: "MS",
    name: "Montserrat",
    phone_code: "+1-664",
    language: "en-MS",
  },
  {
    code: "MA",
    name: "Morocco",
    phone_code: "212",
    language: "ar-MA",
  },
  {
    code: "MZ",
    name: "Mozambique",
    phone_code: "258",
    language: "pt-MZ",
  },
  {
    code: "MM",
    name: "Myanmar",
    phone_code: "95",
    language: "my",
  },
  {
    code: "NA",
    name: "Namibia",
    phone_code: "264",
    language: "en-NA",
  },
  {
    code: "NR",
    name: "Nauru",
    phone_code: "674",
    language: "na",
  },
  {
    code: "NP",
    name: "Nepal",
    phone_code: "977",
    language: "ne",
  },
  {
    code: "AN",
    name: "Netherlands Antilles",
    phone_code: "599",
    language: "nl-AN",
  },
  {
    code: "NL",
    name: "Netherlands",
    phone_code: "31",
    language: "nl-NL",
  },
  {
    code: "NC",
    name: "New Caledonia",
    phone_code: "687",
    language: "fr-NC",
  },
  {
    code: "NZ",
    name: "New Zealand",
    phone_code: "64",
    language: "en-NZ",
  },
  {
    code: "NI",
    name: "Nicaragua",
    phone_code: "505",
    language: "es-NI",
  },
  {
    code: "NE",
    name: "Niger",
    phone_code: "227",
    language: "fr-NE",
  },
  {
    code: "NG",
    name: "Nigeria",
    phone_code: "234",
    language: "en-NG",
  },
  {
    code: "NU",
    name: "Niue",
    phone_code: "683",
    language: "niu",
  },
  {
    code: "NF",
    name: "Norfolk Island",
    phone_code: "672",
    language: "en-NF",
  },
  {
    code: "KP",
    name: "North Korea",
    phone_code: "850",
    language: "ko-KP",
  },
  {
    code: "MP",
    name: "Northern Mariana Islands",
    phone_code: "+1-670",
    language: "fil",
  },
  {
    code: "NO",
    name: "Norway",
    phone_code: "47",
    language: "no",
  },
  {
    code: "OM",
    name: "Oman",
    phone_code: "968",
    language: "ar-OM",
  },
  {
    code: "PK",
    name: "Pakistan",
    phone_code: "92",
    language: "ur-PK",
  },
  {
    code: "PW",
    name: "Palau",
    phone_code: "680",
    language: "pau",
  },
  {
    code: "PS",
    name: "Palestinian Territory",
    phone_code: "970",
    language: "ar-PS",
  },
  {
    code: "PA",
    name: "Panama",
    phone_code: "507",
    language: "es-PA",
  },
  {
    code: "PG",
    name: "Papua New Guinea",
    phone_code: "675",
    language: "en-PG",
  },
  {
    code: "PY",
    name: "Paraguay",
    phone_code: "595",
    language: "es-PY",
  },
  {
    code: "PE",
    name: "Peru",
    phone_code: "51",
    language: "es-PE",
  },
  {
    code: "PH",
    name: "Philippines",
    phone_code: "63",
    language: "tl",
  },
  {
    code: "PN",
    name: "Pitcairn",
    phone_code: "870",
    language: "en-PN",
  },
  {
    code: "PL",
    name: "Poland",
    phone_code: "48",
    language: "pl",
  },
  {
    code: "PT",
    name: "Portugal",
    phone_code: "351",
    language: "pt-PT",
  },
  {
    code: "PR",
    name: "Puerto Rico",
    phone_code: "+1-787 and 1-939",
    language: "en-PR",
  },
  {
    code: "QA",
    name: "Qatar",
    phone_code: "974",
    language: "ar-QA",
  },
  {
    code: "CG",
    name: "Republic of the Congo",
    phone_code: "242",
    language: "fr-CG",
  },
  {
    code: "RE",
    name: "Reunion",
    phone_code: "262",
    language: "fr-RE",
  },
  {
    code: "RO",
    name: "Romania",
    phone_code: "40",
    language: "ro",
  },
  {
    code: "RU",
    name: "Russia",
    phone_code: "7",
    language: "ru",
  },
  {
    code: "RW",
    name: "Rwanda",
    phone_code: "250",
    language: "rw",
  },
  {
    code: "BL",
    name: "Saint Barthelemy",
    phone_code: "590",
    language: "fr",
  },
  {
    code: "SH",
    name: "Saint Helena",
    phone_code: "290",
    language: "en-SH",
  },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    phone_code: "+1-869",
    language: "en-KN",
  },
  {
    code: "LC",
    name: "Saint Lucia",
    phone_code: "+1-758",
    language: "en-LC",
  },
  {
    code: "MF",
    name: "Saint Martin",
    phone_code: "590",
    language: "fr",
  },
  {
    code: "PM",
    name: "Saint Pierre and Miquelon",
    phone_code: "508",
    language: "fr-PM",
  },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    phone_code: "+1-784",
    language: "en-VC",
  },
  {
    code: "WS",
    name: "Samoa",
    phone_code: "685",
    language: "sm",
  },
  {
    code: "SM",
    name: "San Marino",
    phone_code: "378",
    language: "it-SM",
  },
  {
    code: "ST",
    name: "Sao Tome and Principe",
    phone_code: "239",
    language: "pt-ST",
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    phone_code: "966",
    language: "ar-SA",
  },
  {
    code: "SN",
    name: "Senegal",
    phone_code: "221",
    language: "fr-SN",
  },
  {
    code: "CS",
    name: "Serbia and Montenegro",
    phone_code: "381",
    language: "cu",
  },
  {
    code: "RS",
    name: "Serbia",
    phone_code: "381",
    language: "sr",
  },
  {
    code: "SC",
    name: "Seychelles",
    phone_code: "248",
    language: "en-SC",
  },
  {
    code: "SL",
    name: "Sierra Leone",
    phone_code: "232",
    language: "en-SL",
  },
  {
    code: "SG",
    name: "Singapore",
    phone_code: "65",
    language: "cmn",
  },
  {
    code: "SX",
    name: "Sint Maarten",
    phone_code: "599",
    language: "nl",
  },
  {
    code: "SK",
    name: "Slovakia",
    phone_code: "421",
    language: "sk",
  },
  {
    code: "SI",
    name: "Slovenia",
    phone_code: "386",
    language: "sl",
  },
  {
    code: "SB",
    name: "Solomon Islands",
    phone_code: "677",
    language: "en-SB",
  },
  {
    code: "SO",
    name: "Somalia",
    phone_code: "252",
    language: "so-SO",
  },
  {
    code: "ZA",
    name: "South Africa",
    phone_code: "27",
    language: "zu",
  },
  {
    code: "KR",
    name: "South Korea",
    phone_code: "82",
    language: "ko-KR",
  },
  {
    code: "SS",
    name: "South Sudan",
    phone_code: "211",
    language: "en",
  },
  {
    code: "ES",
    name: "Spain",
    phone_code: "34",
    language: "es-ES",
  },
  {
    code: "LK",
    name: "Sri Lanka",
    phone_code: "94",
    language: "si",
  },
  {
    code: "SD",
    name: "Sudan",
    phone_code: "249",
    language: "ar-SD",
  },
  {
    code: "SR",
    name: "Suriname",
    phone_code: "597",
    language: "nl-SR",
  },
  {
    code: "SJ",
    name: "Svalbard and Jan Mayen",
    phone_code: "47",
    language: "no",
  },
  {
    code: "SZ",
    name: "Swaziland",
    phone_code: "268",
    language: "en-SZ",
  },
  {
    code: "SE",
    name: "Sweden",
    phone_code: "46",
    language: "sv-SE",
  },
  {
    code: "CH",
    name: "Switzerland",
    phone_code: "41",
    language: "de-CH",
  },
  {
    code: "SY",
    name: "Syria",
    phone_code: "963",
    language: "ar-SY",
  },
  {
    code: "TW",
    name: "Taiwan",
    phone_code: "886",
    language: "zh-TW",
  },
  {
    code: "TJ",
    name: "Tajikistan",
    phone_code: "992",
    language: "tg",
  },
  {
    code: "TZ",
    name: "Tanzania",
    phone_code: "255",
    language: "sw-TZ",
  },
  {
    code: "TH",
    name: "Thailand",
    phone_code: "66",
    language: "th",
  },
  {
    code: "TG",
    name: "Togo",
    phone_code: "228",
    language: "fr-TG",
  },
  {
    code: "TK",
    name: "Tokelau",
    phone_code: "690",
    language: "tkl",
  },
  {
    code: "TO",
    name: "Tonga",
    phone_code: "676",
    language: "to",
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    phone_code: "+1-868",
    language: "en-TT",
  },
  {
    code: "TN",
    name: "Tunisia",
    phone_code: "216",
    language: "ar-TN",
  },
  {
    code: "TR",
    name: "Turkey",
    phone_code: "90",
    language: "tr-TR",
  },
  {
    code: "TM",
    name: "Turkmenistan",
    phone_code: "993",
    language: "tk",
  },
  {
    code: "TC",
    name: "Turks and Caicos Islands",
    phone_code: "+1-649",
    language: "en-TC",
  },
  {
    code: "TV",
    name: "Tuvalu",
    phone_code: "688",
    language: "tvl",
  },
  {
    code: "VI",
    name: "U.S. Virgin Islands",
    phone_code: "+1-340",
    language: "en-VI",
  },
  {
    code: "UG",
    name: "Uganda",
    phone_code: "256",
    language: "en-UG",
  },
  {
    code: "UA",
    name: "Ukraine",
    phone_code: "380",
    language: "uk",
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    phone_code: "971",
    language: "ar-AE",
  },
  {
    code: "GB",
    name: "United Kingdom",
    phone_code: "44",
    language: "en-GB",
  },
  {
    code: "UM",
    name: "United States Minor Outlying Islands",
    phone_code: "1",
    language: "en-UM",
  },
  {
    code: "US",
    name: "United States",
    phone_code: "1",
    language: "en-US",
  },
  {
    code: "UY",
    name: "Uruguay",
    phone_code: "598",
    language: "es-UY",
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    phone_code: "998",
    language: "uz",
  },
  {
    code: "VU",
    name: "Vanuatu",
    phone_code: "678",
    language: "bi",
  },
  {
    code: "VA",
    name: "Vatican",
    phone_code: "379",
    language: "la",
  },
  {
    code: "VE",
    name: "Venezuela",
    phone_code: "58",
    language: "es-VE",
  },
  {
    code: "VN",
    name: "Vietnam",
    phone_code: "84",
    language: "vi",
  },
  {
    code: "WF",
    name: "Wallis and Futuna",
    phone_code: "681",
    language: "wls",
  },
  {
    code: "EH",
    name: "Western Sahara",
    phone_code: "212",
    language: "ar",
  },
  {
    code: "YE",
    name: "Yemen",
    phone_code: "967",
    language: "ar-YE",
  },
  {
    code: "ZM",
    name: "Zambia",
    phone_code: "260",
    language: "en-ZM",
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    phone_code: "263",
    language: "en-ZW",
  },
];

// ------------------------- COLLECTION -------------------------

const COLLECTION_NAME = NAME.COUNTRY;

const COLLECTION = db.collection(COLLECTION_NAME);

// ------------------------- Commands ---------------------------

/**
 *
 * @param {import("@src/utils/DBTransaction").DBTransaction} DBT
 * @returns {Promise<void>}
 */
exports.up = async function up(DBT) {
  await db.createCollection(COLLECTION_NAME, DBT.mongoose());

  await COLLECTION.createIndexes(
    [
      {
        key: {
          code: 1,
        },
        unique: true,
      },
      {
        key: {
          phone_code: 1,
        },
      },
      {
        key: {
          language: 1,
        },
      },
    ],
    DBT.mongoose(),
  );

  const now = new Date();

  await COLLECTION.insertMany(
    COUNTRIES.map(country => ({
      ...country,
      created_at: now,
      updated_at: now,
    })),
    {
      ordered: true,
      session: DBT.session,
    },
  );
};

exports.down = async function down() {
  const collections = await db.listCollections().toArray();

  if (collections.findIndex(collection => collection.name === COLLECTION_NAME) === -1) return;

  await COLLECTION.drop();
};
